# Generated by Django 4.0.5 on 2022-10-01 15:01

from django.db import migrations, models
import django.db.models.deletion
import test_many_to_one.models


class Migration(migrations.Migration):

    dependencies = [
        ('test_many_to_one', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(default=test_many_to_one.models.Question1.pub_date_default, verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Choice1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='test_many_to_one.question1')),
            ],
        ),
    ]
