site_name: Django To Rest Docs
dev_addr: 127.0.0.1:8080
site_url: https://anp-scp.github.io/django-to-rest
repo_url: https://github.com/anp-scp/django-to-rest

nav:
  - index.md
  - quickstart.md
  - 'Full Guide':
    - full_guide/marking_model_for_REST.md
    - full_guide/adding_custom_serializer.md
    - full_guide/adding_custom_auth.md
    - full_guide/adding_custom_permission.md
    - full_guide/adding_custom_throttling.md

theme: 
  name: material
  custom_dir: docs_overrides
  icon:
    logo: material/book
  favicon: img/small_logo_grey.png
  features:
    - navigation.tabs
    - navigation.top
    - header.autohide
    - navigation.tabs.sticky
    - content.code.annotate
  font:
    text: Roboto Condensed
    code: Roboto Mono
  palette: 
    - scheme: default
      primary: blue grey
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue grey
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light mode


markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
