site_name: Django To Rest Docs
theme: 
  name: material
  logo: img/small_logo_grey.png
  favicon: img/small_logo_grey.png
  features:
    - navigation.tabs
    - header.autohide
    - navigation.top
  font:
    text: Roboto Condensed
    code: Roboto Mono
  palette: 
    - scheme: default
      primary: blue grey
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue grey
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode


markdown_extensions:
  - attr_list
  - md_in_html
