# Generated by Django 4.0.5 on 2022-07-10 11:05

from django.db import migrations, models
import test_basics_defaults.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('year', models.IntegerField(validators=[test_basics_defaults.models.is_valid_year])),
            ],
        ),
    ]
