# Generated by Django 4.0.5 on 2022-07-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_basics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentWithCustomSerializer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
