name: Publish Python distributions to PyPI and TestPyPI
on:
    push:
      branches: [master]
    pull_request:
      branches: [master]

jobs:
  build-test-publish:
    name: Publish Python distributions to PyPI and TestPyPI
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@master
      -
        name: Setup python 3.8.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.8.10"
      -
        name: Setup build env
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install setuptools
      -
        name: Perform testing
        run: |
          python3 -m install ./
          cd tests
          python3 manage.py test test_basics
          python3 manage.py test test_basics_defaults --settings=tests.settings_test_basics_defaults
      -
        name: Build the distribution
        run: |
          python3 setup.py sdist
      -
        name: Publish to Test PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
      -
        name: Publish to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
