#options
GET_OBJECT_LIST = "GET_OBJECT_LIST"
GET_OBJECT = "GET_OBJECT"
CREATE_OBJECT = "CREATE_OBJECT"
UPDATE_OBJECT = "UPDATE_OBJECT"
PATCH_OBJECT = "PATCH_OBJECT"
DELETE_OBJECT = "UPDATE_OBJECT"
CUSTOM_VIEWS = "CUSTOM_VIEWS"
EXCLUDE_FIELDS = "EXCLUDE_FIELDS"
SEARCH_FIELDS = "SEARCH_FIELDS"
METHOD_FIELDS = "METHOD_FIELDS"
CUSTOM_SERIALIZER = "CUSTOM_SERIALIZER"


#messages
NOT_A_MODEL_CLASS_MSG = "The decorated class must be a sub class django.db.models.Model"